services:
  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=Group2"
      - "POSTGRES_PASSWORD=passpass"
      - "POSTGRES_USER=postgres"
    ports:
      - "5432:5432"
    #    volumes:
    #      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  frontend-feedback-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://feedback-api:8080/api/v1

  feedback-api:
    build:
      context: ../tsg-9.27-Group2-feedback-api
      dockerfile: Dockerfile
    container_name: feedback-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Group2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: passpass

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    ports:
      - "8080:8080" # required so the frontend can call the API

  kafka:
    image: confluentinc/confluent-local:latestt
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Single-node KRaft mode (no Zookeeper)
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka_data:/bitnami/kafka

#  kafbat-ui:
#    container_name: kafbat-ui
#    image: ghcr.io/kafbat/kafka-ui:latest
#    ports:
#    - 8080:8080
#    environment:
#      DYNAMIC_CONFIG_ENABLED: 'true'

volumes:
  kafka_data:
  #pg_data:
