# frontend-feedback-ui:
#   build: ./frontend-feedback-ui
#   container_name: frontend-feedback-ui
#   ports:
#     - "5173:80"
#   environment:
#     - VITE_API_BASE_URL=http://feedback-api:8080/api/v1
#   depends_on:
#     - feedback-api

version: "3.8"

services:
  frontend-feedback-ui:
    build: .
    container_name: frontend-feedback-ui
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://feedback-api:8080/api/v1
